name: CI

on:
  push:
    branches: [main]
    
jobs:
  test:
    name: Test Core
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repositiory
        uses: actions/checkout@v3
        
      - name: Test
        run: cargo test
